const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/sequelize');

module.exports = sequelize.define('TourRequest', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  userId: { type: DataTypes.STRING },
  userName: { type: DataTypes.STRING },
  requestedBy: { type: DataTypes.STRING },
  requestedByName: { type: DataTypes.STRING },
  reqId: { type: DataTypes.STRING },
  timestamp: { type: DataTypes.STRING },
  destination: { type: DataTypes.STRING },
  purpose: { type: DataTypes.TEXT },
  startDate: { type: DataTypes.STRING },
  endDate: { type: DataTypes.STRING },
  status: { type: DataTypes.STRING, defaultValue: "Pending Review" },
  estimatedFare: { type: DataTypes.FLOAT, defaultValue: 0 },
  advanceRequested: { type: DataTypes.FLOAT, defaultValue: 0 },
  advanceMode: { type: DataTypes.STRING, defaultValue: "" },
  hotelName: { type: DataTypes.STRING, defaultValue: "" },
  hotelNights: { type: DataTypes.INTEGER, defaultValue: 0 },
  hotelRate: { type: DataTypes.FLOAT, defaultValue: 0 },
  hotelBookingRef: { type: DataTypes.STRING, defaultValue: "" },
  bookingRef: { type: DataTypes.STRING, defaultValue: "" },
  travelClass: { type: DataTypes.STRING, defaultValue: "" },
  department: { type: DataTypes.STRING, defaultValue: "" },
  mealDays: { type: DataTypes.INTEGER, defaultValue: 0 },
  mealRate: { type: DataTypes.FLOAT, defaultValue: 0 },
  specialRemarks: { type: DataTypes.TEXT, defaultValue: "" },
  preTravelDocuments: { type: DataTypes.JSON, defaultValue: [] },
  reimbursementBills: { type: DataTypes.JSON, defaultValue: [] },
  reimDate: { type: DataTypes.STRING, defaultValue: "" },
  actualDeparture: { type: DataTypes.STRING, defaultValue: "" },
  actualReturn: { type: DataTypes.STRING, defaultValue: "" },
  actualTravelMode: { type: DataTypes.STRING, defaultValue: "" },
  actualDistance: { type: DataTypes.STRING, defaultValue: "" },
  actualAdvanceReceived: { type: DataTypes.FLOAT, defaultValue: 0 },
  actualAdvanceRef: { type: DataTypes.STRING, defaultValue: "" },
  tripOutcome: { type: DataTypes.TEXT, defaultValue: "" },
  outcomeNextSteps: { type: DataTypes.TEXT, defaultValue: "" },
  employeeRemarks: { type: DataTypes.TEXT, defaultValue: "" },
  reimbursementStatus: { type: DataTypes.STRING, defaultValue: "" },
  actualExpenses: { type: DataTypes.JSON, defaultValue: {} },
  approvedExpenses: { type: DataTypes.JSON, defaultValue: {} },
  expenseRemarks: { type: DataTypes.JSON, defaultValue: {} }
}, { tableName: 'tour_requests', timestamps: true });