const mongoose = require('mongoose');

const caseSchema = new mongoose.Schema({
  caseId: { type: String, unique: true },
  createdDate: String,
  companyName: String,
  caseTitle: String,
  priority: { type: String, enum: ["High","Medium","Low"] },
  sourceOfComplaint: String,
  typeOfComplaint: String,
  brandName: String,
  serviceMode: { type: String, default: "Single Service" },
  servicesSold: [],
  engagementNote: String,
  clientName: String,
  clientMobile: String,
  clientEmail: String,
  state: String,
  totalAmtPaid: String,
  mouSigned: String,
  totalMouValue: String,
  amtInDispute: String,
  smRisk: String,
  complaint: String,
  policeThreat: String,
  caseSummary: String,
  clientAllegation: String,
  proofCallRec: String,
  proofWaChat: String,
  proofVideoCall: String,
  proofFundingEmail: String,
  initiatedBy: String,
  accountable: String,
  legalOfficer: String,
  accounts: String,
  caseCreatedSource: { type: String, default: "Form" },
  currentStatus: { type: String, default: "New" },
  lastUpdateDate: String,
  nextActionDate: String,
  cyberAckNumbers: String,
  firNumber: String,
  firFileLink: String,
  grievanceNumber: String,
  caseStudyGeneratedAt: String,
  assignedTo: String,
  progressPercentage: { type: Number, default: 0 }
}, { timestamps: true });

module.exports = mongoose.model('Case', caseSchema);
